## ESR 514 Numeriacal Methord and Algorithoms in RS and GIS
## Assignment number 2-numpy

### MSc/GIS/19/11

## Question Number 1

In [1]:
#import numpy 
import numpy as np

## Question Number 2

In [ ]:
#Print the numpy version and the cofigratio
print("numpy version is",np.__version__)
print(np.show_config())

## Question Number 3

In [2]:
x = np.zeros(5)
print(x)

[0. 0. 0. 0. 0.]


## Question Number 4

In [3]:
x = np.eye(10)
print(x)

print("Size of the array: ",x.size)   
#print("Memory size of one array element in bytes: ",x.itemsize) 
  
# memory size of numpy array in bytes 
print("Memory size of numpy array in bytes:",x.size * x.itemsize)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
Size of the array:  100
Memory size of numpy array in bytes: 800


## Question Number 5

In [4]:
x = np.arange(0,255)
print(x)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 24

## Question Number 6

In [5]:
x = np.array([0,1,2,3,4,5,6,7,8,9])
print(x)

x = np.flipud(x) 
print(x)    

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


## Question Number 7

In [6]:
x = np.random.randint(low=0, high=10, size=(5, 5))
print(x)

[[7 2 9 5 4]
 [7 3 2 9 7]
 [5 2 8 2 8]
 [4 7 3 4 0]
 [8 5 1 0 2]]


## Question Number 8

In [4]:
x = np.array([19,12,0,-5,0,4,-6])
print(x)

print("this is the index of -5 ",np.where(x == -5))

print("this is the indices of non-zero values",np.where(x!= 0))

print("minimum value is",np.min(x))

print("maximum value is ",np.max(x))


[19 12  0 -5  0  4 -6]
this is the index of -5  (array([3], dtype=int64),)
this is the indices of non-zero values (array([0, 1, 3, 5, 6], dtype=int64),)
minimum value is -6
maximum value is  19


## Question Number 9

In [5]:
x = np.ones((8,8),dtype=int)
x[:1,:8] = 0
x[:8,:1] = 0
x[:8,7:8]=0
x[7:8,:8]=0
print(x)

[[0 0 0 0 0 0 0 0]
 [0 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 0]
 [0 0 0 0 0 0 0 0]]


## Question Number 10

In [3]:
x = np.array([[12,4,6,0,55,6],[19,7,0,1,8,0],[99,12,3,4,2,32],[6,1,23,0,45,54],[78,0,156,124,7,73],[0,41,0,7,6,21]])
print(x)

[[ 12   4   6   0  55   6]
 [ 19   7   0   1   8   0]
 [ 99  12   3   4   2  32]
 [  6   1  23   0  45  54]
 [ 78   0 156 124   7  73]
 [  0  41   0   7   6  21]]


10 a
Normalization is the process of castong the data to the specific range. it may be between 0-1 or -1 to +1.

10 b Normalization is requred when there are big differences in the ranges of differnt features.

10 c

In [6]:
x = np.array([[12,4,6,0,55,6],[19,7,0,1,8,0],[99,12,3,4,2,32],[6,1,23,0,45,54],[78,0,156,124,7,73],[0,41,0,7,6,21]])
print(x)
x = x/np.linalg.norm(x)
print(x)

[[ 12   4   6   0  55   6]
 [ 19   7   0   1   8   0]
 [ 99  12   3   4   2  32]
 [  6   1  23   0  45  54]
 [ 78   0 156 124   7  73]
 [  0  41   0   7   6  21]]
[[0.04422718 0.01474239 0.02211359 0.         0.2027079  0.02211359]
 [0.07002637 0.02579919 0.         0.0036856  0.02948479 0.        ]
 [0.36487423 0.04422718 0.01105679 0.01474239 0.0073712  0.11793914]
 [0.02211359 0.0036856  0.08476876 0.         0.16585192 0.19902231]
 [0.28747666 0.         0.57495333 0.45701418 0.02579919 0.26904867]
 [0.         0.15110953 0.         0.02579919 0.02211359 0.07739756]]


10 d

In [8]:
x = x.reshape(4,9)
print(x)

[[0.04422718 0.01474239 0.02211359 0.         0.2027079  0.02211359
  0.07002637 0.02579919 0.        ]
 [0.0036856  0.02948479 0.         0.36487423 0.04422718 0.01105679
  0.01474239 0.0073712  0.11793914]
 [0.02211359 0.0036856  0.08476876 0.         0.16585192 0.19902231
  0.28747666 0.         0.57495333]
 [0.45701418 0.02579919 0.26904867 0.         0.15110953 0.
  0.02579919 0.02211359 0.07739756]]


## Question Number 11

In [ ]:
print(np.array(0)/np.array(0))

In [ ]:
print(np.array(0)//np.array(0))

### in first command i got answer as nan. that means not a number. it is a normal division. but in second command i got 0. it is flour division. it's returned a number.

## Question Number 12

In [ ]:
daybeforeyesterday = np.datetime64('today', 'D') - np.timedelta64(2, 'D')
print("Day Before Yestraday: ",daybeforeyesterday)
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

## Question Number 13

In [8]:
x = np.random.randint(low=0,high=50,size=15)
print(x)
#sort in ascending order
x = np.sort(x)
print(x)
#sort in descending order
x =-np.sort(-x)
print(x)

[37 34 46 43  1 30 12 10 24 10  9 32 42 11  0]
[ 0  1  9 10 10 11 12 24 30 32 34 37 42 43 46]
[46 43 42 37 34 32 30 24 12 11 10 10  9  1  0]


## Question Number 14

In [ ]:
p = np.random.random(10)*5
print("array p \n",p)
q = np.random.random(10)*5
print("array q \n",q)

if np.array_equal(p,q)==False:
    print("Two arrays are not equal")
else:
    print("Two arrays are equal")

## Question Number 15

In [ ]:
Ex = np.array([{'USD':195.91,'EUR':233.45,'GBP':271.14}])
#print(x)
play = True
while play:
    currency = input("Please select your currency type:\nUSD\nEUR\nGBP\n")
    x = float(input("Enter your currency ammount: "))
    #print(currrency)
    while True:
        if currency == 'USD':
            print("Your US doller ammount is equal to Rs:",x*float(Ex[0]['USD']))
            break
        elif currency == 'EUR':
            print("Your Euro ammount is equal to Rs:",x*float(Ex[0]['EUR']))
            break
        elif currency == 'GBP':
            print("Your GB pound ammount is equal to Rs:",x*float(Ex[0]['GBP']))
            break
        else:
            curency =float(input("Select corret option!"))

    ans = input("Do you want convert again :(y/n)")
    if ans =='y':
        continue
    else:
        print("Thank you for used my currency converter!\n Have a nice day!")
        break  